# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('semester', models.CharField(max_length=10)),
                ('class_code', models.CharField(max_length=6)),
                ('class_password', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
