# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_auto_20171031_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
