# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 22:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class', '0006_option_optionstudrelation_poll'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optionstudrelation',
            unique_together=set([('option_id', 'stud_id')]),
        ),
    ]
